# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grpp/UFPR/Periodo_Especial/Prog_II/fotomosaico

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grpp/UFPR/Periodo_Especial/Prog_II/fotomosaico

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grpp/UFPR/Periodo_Especial/Prog_II/fotomosaico/CMakeFiles /home/grpp/UFPR/Periodo_Especial/Prog_II/fotomosaico//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grpp/UFPR/Periodo_Especial/Prog_II/fotomosaico/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mosaico

# Build rule for target.
mosaico: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mosaico
.PHONY : mosaico

# fast build rule for target.
mosaico/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/build
.PHONY : mosaico/fast

libtiles.o: libtiles.c.o
.PHONY : libtiles.o

# target to build an object file
libtiles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/libtiles.c.o
.PHONY : libtiles.c.o

libtiles.i: libtiles.c.i
.PHONY : libtiles.i

# target to preprocess a source file
libtiles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/libtiles.c.i
.PHONY : libtiles.c.i

libtiles.s: libtiles.c.s
.PHONY : libtiles.s

# target to generate assembly for a file
libtiles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/libtiles.c.s
.PHONY : libtiles.c.s

mosaico.o: mosaico.c.o
.PHONY : mosaico.o

# target to build an object file
mosaico.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/mosaico.c.o
.PHONY : mosaico.c.o

mosaico.i: mosaico.c.i
.PHONY : mosaico.i

# target to preprocess a source file
mosaico.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/mosaico.c.i
.PHONY : mosaico.c.i

mosaico.s: mosaico.c.s
.PHONY : mosaico.s

# target to generate assembly for a file
mosaico.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mosaico.dir/build.make CMakeFiles/mosaico.dir/mosaico.c.s
.PHONY : mosaico.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mosaico"
	@echo "... libtiles.o"
	@echo "... libtiles.i"
	@echo "... libtiles.s"
	@echo "... mosaico.o"
	@echo "... mosaico.i"
	@echo "... mosaico.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

